# Generated by Django 5.2.1 on 2025-11-06 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offline_sales', '0001_initial'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billreturn',
            name='returned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_returns_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billreturnitem',
            name='bill_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_items', to='offline_sales.billreturn'),
        ),
        migrations.AddField(
            model_name='offlinesale',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_sales_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offlinesale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_sales', to='offline_sales.offlinecustomer'),
        ),
        migrations.AddField(
            model_name='offlinesale',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_sales_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billreturn',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='offline_sales.offlinesale'),
        ),
        migrations.AddField(
            model_name='offlinesaleitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.batch'),
        ),
        migrations.AddField(
            model_name='offlinesaleitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='offlinesaleitem',
            name='product_unit',
            field=models.ForeignKey(blank=True, help_text="The unit in which this product was sold (e.g., 'strip', 'bottle').", null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productunit'),
        ),
        migrations.AddField(
            model_name='offlinesaleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='offline_sales.offlinesale'),
        ),
        migrations.AddField(
            model_name='billreturnitem',
            name='offline_sale_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_details', to='offline_sales.offlinesaleitem'),
        ),
    ]
