# Generated by Django 4.2.13 on 2025-11-05 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('offline_sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinesaleitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.batch'),
        ),
        migrations.AddField(
            model_name='offlinesaleitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='offlinesaleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='offline_sales.offlinesale'),
        ),
    ]
