# Generated by Django 4.2.13 on 2025-11-05 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offline_sales', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinesale',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_sales_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offlinesale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_sales', to='offline_sales.offlinecustomer'),
        ),
        migrations.AddField(
            model_name='offlinesale',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_sales_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billreturnitem',
            name='bill_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_items', to='offline_sales.billreturn'),
        ),
        migrations.AddField(
            model_name='billreturnitem',
            name='offline_sale_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_details', to='offline_sales.offlinesaleitem'),
        ),
        migrations.AddField(
            model_name='billreturn',
            name='returned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_returns_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billreturn',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='offline_sales.offlinesale'),
        ),
    ]
