# Generated by Django 5.2.1 on 2025-10-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offline_sales', '0003_offlinecustomer_offlinesale_customer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlinecustomer',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
