# Generated by Django 4.2.13 on 2025-11-05 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
        ('offline_sales', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinesaleitem',
            name='product_unit',
            field=models.ForeignKey(blank=True, help_text="The unit in which this product was sold (e.g., 'strip', 'bottle').", null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productunit'),
        ),
    ]
