# Generated by Django 5.2.1 on 2025-10-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offline_sales', '0004_alter_offlinecustomer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offlinesale',
            name='is_returned',
        ),
        migrations.RemoveField(
            model_name='offlinesale',
            name='return_date',
        ),
        migrations.AddField(
            model_name='billreturn',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='offlinesale',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offlinesale',
            name='last_status_update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='offlinesale',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned'), ('PARTIALLY_RETURNED', 'Partially Returned')], default='PENDING', max_length=20),
        ),
    ]
