# Generated by Django 5.2.1 on 2025-10-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offline_sales', '0005_remove_offlinesale_is_returned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinesaleitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='offlinesaleitem',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
