# Generated by Django 5.2.1 on 2025-10-30 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offline_sales', '0006_offlinesaleitem_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinesale',
            name='tag',
            field=models.CharField(choices=[('OFFLINE', 'Offline Sale'), ('ONLINE', 'Online Sale')], default='OFFLINE', max_length=20),
        ),
    ]
