# Generated by Django 5.2.3 on 2025-06-29 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField()),
                ('recognized_text_raw', models.TextField()),
                ('ai_extracted_medicine_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_extracted_dosage', models.CharField(blank=True, max_length=100, null=True)),
                ('ai_extracted_quantity', models.CharField(blank=True, max_length=50, null=True)),
                ('ai_extracted_instructions', models.TextField(blank=True, null=True)),
                ('ai_confidence_score', models.FloatField(blank=True, null=True)),
                ('verified_medicine_name', models.CharField(blank=True, max_length=255, null=True)),
                ('verified_dosage', models.CharField(blank=True, max_length=100, null=True)),
                ('verified_quantity', models.CharField(blank=True, max_length=50, null=True)),
                ('verified_instructions', models.TextField(blank=True, null=True)),
                ('mapping_status', models.CharField(max_length=50)),
                ('is_valid_for_order', models.BooleanField(default=False)),
                ('pharmacist_comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('image_url', models.URLField()),
                ('verification_status', models.CharField(choices=[('Uploaded', 'Uploaded'), ('AI_Processed', 'AI_Processed'), ('Pending_Review', 'Pending_Review'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Uploaded', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('pharmacist_notes', models.TextField(blank=True, null=True)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_upload', to='orders.order')),
            ],
        ),
    ]
