# Generated by Django 4.2.13 on 2025-11-05 02:35

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('match_type', models.CharField(max_length=50)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('search_term', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Medicine Suggestion',
                'verbose_name_plural': 'Medicine Suggestions',
                'db_table': 'medicine_suggestions',
                'ordering': ['-confidence_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prescription_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('patient_name', models.CharField(blank=True, max_length=200, null=True)),
                ('patient_age', models.PositiveIntegerField(blank=True, null=True)),
                ('patient_gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('doctor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('doctor_license', models.CharField(blank=True, max_length=100, null=True)),
                ('hospital_clinic', models.CharField(blank=True, max_length=300, null=True)),
                ('prescription_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('ai_processing', 'AI Processing'), ('ai_mapped', 'AI Mapped'), ('pending_verification', 'Pending Verification'), ('verified', 'Verified'), ('need_clarification', 'Need Clarification'), ('rejected', 'Rejected'), ('dispensed', 'Dispensed'), ('completed', 'Completed')], default='uploaded', max_length=30)),
                ('verification_status', models.CharField(choices=[('Uploaded', 'Uploaded'), ('AI_Processing', 'AI_Processing'), ('AI_Processed', 'AI_Processed'), ('Pending_Review', 'Pending_Review'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Uploaded', max_length=20)),
                ('image_url', models.URLField(blank=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='prescriptions/')),
                ('ocr_text', models.TextField(blank=True)),
                ('ai_confidence_score', models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('ai_processing_time', models.FloatField(blank=True, null=True)),
                ('ai_processed', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('clarification_notes', models.TextField(blank=True, null=True)),
                ('pharmacist_notes', models.TextField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'db_table': 'prescriptions',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionMedicine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_number', models.PositiveIntegerField(default=1)),
                ('recognized_text_raw', models.TextField(blank=True)),
                ('extracted_medicine_name', models.CharField(max_length=300)),
                ('extracted_dosage', models.CharField(blank=True, max_length=100)),
                ('extracted_frequency', models.CharField(blank=True, max_length=100)),
                ('extracted_duration', models.CharField(blank=True, max_length=100)),
                ('extracted_quantity', models.CharField(blank=True, max_length=50)),
                ('extracted_instructions', models.TextField(blank=True)),
                ('extracted_form', models.CharField(blank=True, max_length=100)),
                ('ai_confidence_score', models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('need_clarification', 'Need Clarification'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verified_medicine_name', models.CharField(blank=True, max_length=255, null=True)),
                ('verified_dosage', models.CharField(blank=True, max_length=100, null=True)),
                ('verified_frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('verified_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('verified_quantity', models.CharField(blank=True, max_length=50, null=True)),
                ('verified_instructions', models.TextField(blank=True, null=True)),
                ('quantity_prescribed', models.PositiveIntegerField(default=1)),
                ('quantity_dispensed', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_valid_for_order', models.BooleanField(default=False)),
                ('customer_approved', models.BooleanField(default=False)),
                ('pharmacist_comment', models.TextField(blank=True, null=True)),
                ('clarification_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prescription Medicine',
                'verbose_name_plural': 'Prescription Medicines',
                'db_table': 'prescription_medicines',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_text', models.TextField()),
                ('extracted_medicines', models.JSONField(default=list)),
                ('total_suggestions', models.IntegerField(default=0)),
                ('scan_type', models.CharField(choices=[('composition_search', 'Composition Search'), ('ocr_scan', 'OCR Scan'), ('manual_entry', 'Manual Entry')], default='composition_search', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Prescription Scan Result',
                'verbose_name_plural': 'Prescription Scan Results',
                'db_table': 'prescription_scan_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionWorkflowLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('action', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('system_generated', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Prescription Workflow Log',
                'verbose_name_plural': 'Prescription Workflow Logs',
                'db_table': 'prescription_workflow_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
