# Generated by Django 5.2.1 on 2025-08-02 06:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionMedicine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_number', models.PositiveIntegerField(default=1)),
                ('recognized_text_raw', models.TextField(blank=True)),
                ('extracted_medicine_name', models.CharField(max_length=300)),
                ('extracted_dosage', models.CharField(blank=True, max_length=100)),
                ('extracted_frequency', models.CharField(blank=True, max_length=100)),
                ('extracted_duration', models.CharField(blank=True, max_length=100)),
                ('extracted_quantity', models.CharField(blank=True, max_length=50)),
                ('extracted_instructions', models.TextField(blank=True)),
                ('ai_confidence_score', models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('need_clarification', 'Need Clarification'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('mapping_status', models.CharField(choices=[('Pending', 'Pending'), ('Mapped', 'Mapped'), ('Unmapped', 'Unmapped'), ('Unavailable', 'Unavailable')], default='Pending', max_length=50)),
                ('verified_medicine_name', models.CharField(blank=True, max_length=255, null=True)),
                ('verified_dosage', models.CharField(blank=True, max_length=100, null=True)),
                ('verified_frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('verified_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('verified_quantity', models.CharField(blank=True, max_length=50, null=True)),
                ('verified_instructions', models.TextField(blank=True, null=True)),
                ('quantity_prescribed', models.PositiveIntegerField(default=1)),
                ('quantity_dispensed', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_valid_for_order', models.BooleanField(default=False)),
                ('customer_approved', models.BooleanField(default=False)),
                ('pharmacist_comment', models.TextField(blank=True, null=True)),
                ('clarification_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prescription Medicine',
                'verbose_name_plural': 'Prescription Medicines',
                'db_table': 'prescription_medicines',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionWorkflowLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('action_taken', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('system_generated', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Prescription Workflow Log',
                'verbose_name_plural': 'Prescription Workflow Logs',
                'db_table': 'prescription_workflow_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prescription_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('patient_name', models.CharField(blank=True, max_length=200, null=True)),
                ('patient_age', models.PositiveIntegerField(blank=True, null=True)),
                ('patient_gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('doctor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('doctor_license', models.CharField(blank=True, max_length=100, null=True)),
                ('hospital_clinic', models.CharField(blank=True, max_length=300, null=True)),
                ('prescription_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('ai_processing', 'AI Processing'), ('ai_mapped', 'AI Mapped'), ('pending_verification', 'Pending Verification'), ('verified', 'Verified'), ('need_clarification', 'Need Clarification'), ('rejected', 'Rejected'), ('dispensed', 'Dispensed'), ('completed', 'Completed')], default='uploaded', max_length=30)),
                ('verification_status', models.CharField(choices=[('Uploaded', 'Uploaded'), ('AI_Processing', 'AI_Processing'), ('AI_Processed', 'AI_Processed'), ('Pending_Review', 'Pending_Review'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Uploaded', max_length=20)),
                ('image_url', models.URLField(blank=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='prescriptions/')),
                ('ocr_text', models.TextField(blank=True)),
                ('ai_confidence_score', models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('ai_processing_time', models.FloatField(blank=True, null=True)),
                ('ai_processed', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('clarification_notes', models.TextField(blank=True, null=True)),
                ('pharmacist_notes', models.TextField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_upload', to='orders.order')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'db_table': 'prescriptions',
            },
        ),
    ]
