# Generated by Django 4.2.13 on 2025-11-05 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionworkflowlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescriptionworkflowlog',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_logs', to='prescriptions.prescription'),
        ),
        migrations.AddField(
            model_name='prescriptionscanresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='mapped_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product'),
        ),
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_medicines', to='prescriptions.prescription'),
        ),
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='suggested_medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_suggestions', to='product.product'),
        ),
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='suggested_products',
            field=models.ManyToManyField(blank=True, related_name='suggested_for_prescriptions', to='product.product'),
        ),
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_medicines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='verified_medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_prescriptions', to='product.product'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescription',
            name='verified_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_prescriptions_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicinesuggestion',
            name='scan_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='prescriptions.prescriptionscanresult'),
        ),
        migrations.AddIndex(
            model_name='prescriptionmedicine',
            index=models.Index(fields=['verification_status'], name='prescriptio_verific_0f07bc_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptionmedicine',
            index=models.Index(fields=['ai_confidence_score'], name='prescriptio_ai_conf_3923dc_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['status'], name='prescriptio_status_1d7db8_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['verification_status'], name='prescriptio_verific_8b0c24_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['upload_date'], name='prescriptio_upload__c7c877_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['prescription_number'], name='prescriptio_prescri_b8a9ac_idx'),
        ),
    ]
