# Generated by Django 5.2.4 on 2025-08-05 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_text', models.TextField()),
                ('extracted_medicines', models.JSONField(default=list)),
                ('total_suggestions', models.IntegerField(default=0)),
                ('scan_type', models.CharField(choices=[('composition_search', 'Composition Search'), ('ocr_scan', 'OCR Scan'), ('manual_entry', 'Manual Entry')], default='composition_search', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prescription Scan Result',
                'verbose_name_plural': 'Prescription Scan Results',
                'db_table': 'prescription_scan_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicineSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('match_type', models.CharField(max_length=50)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('search_term', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='prescriptions.prescriptionscanresult')),
            ],
            options={
                'verbose_name': 'Medicine Suggestion',
                'verbose_name_plural': 'Medicine Suggestions',
                'db_table': 'medicine_suggestions',
                'ordering': ['-confidence_score', '-created_at'],
            },
        ),
    ]
