# Generated by Django 5.2.3 on 2025-07-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='ai_processing_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='prescriptions/'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescription_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptiondetail',
            name='ai_extracted_duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prescriptiondetail',
            name='ai_extracted_frequency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prescriptiondetail',
            name='customer_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescriptiondetail',
            name='suggested_products',
            field=models.ManyToManyField(blank=True, related_name='suggested_for_prescriptions', to='product.product'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='verification_status',
            field=models.CharField(choices=[('Uploaded', 'Uploaded'), ('AI_Processing', 'AI_Processing'), ('AI_Processed', 'AI_Processed'), ('Pending_Review', 'Pending_Review'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Uploaded', max_length=20),
        ),
        migrations.AlterField(
            model_name='prescriptiondetail',
            name='mapping_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Mapped', 'Mapped'), ('Unmapped', 'Unmapped'), ('Unavailable', 'Unavailable')], default='Pending', max_length=50),
        ),
    ]
