# Generated by Django 5.2.1 on 2025-09-13 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_prescriptionscanresult_medicinesuggestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='order',
        ),
    ]
