# Generated by Django 5.2.1 on 2025-09-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0004_remove_prescription_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='extracted_form',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
