# Generated by Django 5.2.1 on 2025-10-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0005_prescriptionmedicine_extracted_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionmedicine',
            name='suggested_medicine',
        ),
        migrations.RemoveField(
            model_name='prescriptionmedicine',
            name='suggested_products',
        ),
        migrations.AlterField(
            model_name='prescription',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='prescriptions/img/'),
        ),
    ]
