# Generated by Django 5.2.1 on 2025-10-05 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0007_remove_prescriptionmedicine_prescriptio_mapping_4f121f_idx_and_more'),
        ('product', '0003_composition_aliases_composition_mechanism_of_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='mapping_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Mapped', 'Mapped'), ('Unmapped', 'Unmapped'), ('Unavailable', 'Unavailable')], default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='suggested_medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_suggestions', to='product.product'),
        ),
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='suggested_products',
            field=models.ManyToManyField(blank=True, related_name='suggested_for_prescriptions', to='product.product'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='prescriptions/'),
        ),
        migrations.AddIndex(
            model_name='prescriptionmedicine',
            index=models.Index(fields=['mapping_status'], name='prescriptio_mapping_4f121f_idx'),
        ),
    ]
