# Generated by Django 5.2.1 on 2025-10-05 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0008_prescriptionmedicine_mapping_status_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='prescriptionmedicine',
            name='prescriptio_mapping_4f121f_idx',
        ),
        migrations.RemoveField(
            model_name='prescriptionmedicine',
            name='mapping_status',
        ),
    ]
