# Generated by Django 5.2.1 on 2025-10-13 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0009_remove_prescriptionmedicine_prescriptio_mapping_4f121f_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescriptionworkflowlog',
            old_name='action_taken',
            new_name='action',
        ),
        migrations.RenameField(
            model_name='prescriptionworkflowlog',
            old_name='performed_by',
            new_name='actor',
        ),
    ]
