# Generated by Django 5.2.1 on 2025-10-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0010_rename_action_taken_prescriptionworkflowlog_action_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='prescription',
            name='prescriptio_verific_8b0c24_idx',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='verification_status',
        ),
        migrations.RemoveField(
            model_name='prescriptionmedicine',
            name='mapped_product',
        ),
        migrations.RemoveField(
            model_name='prescriptionscanresult',
            name='scanned_text',
        ),
        migrations.AlterField(
            model_name='medicinesuggestion',
            name='product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionmedicine',
            name='extracted_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionmedicine',
            name='verified_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
