# Generated by Django 4.2.13 on 2025-11-06 10:05

from django.db import migrations
import django.db.models.deletion


def populate_user_roles(apps, schema_editor):
    User = apps.get_model('usermanagement', 'User')
    UserRole = apps.get_model('usermanagement', 'UserRole')

    try:
        # Ensure 'customer' role exists, create if not
        customer_role, created = UserRole.objects.get_or_create(
            name='customer',
            defaults={'display_name': 'Customer', 'description': 'Default customer role'}
        )
        
        # Update users with null user_role to 'customer'
        User.objects.filter(user_role__isnull=True).update(user_role=customer_role)
    except Exception as e:
        print(f"Error populating user roles: {e}")
        # Depending on the environment, you might want to raise the exception
        # or log it more robustly. For a migration, it's often better to let it fail
        # if critical data cannot be set.

class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_user_roles, reverse_code=migrations.RunPython.noop),
    ]
