# Generated by Django 5.2.1 on 2025-10-29 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_remove_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
