# Generated by Django 4.2.13 on 2025-11-06 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0004_alter_user_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='usermanagement.userrole'),
        ),
    ]
