# Generated by Django 4.2.13 on 2025-11-06 10:17

from django.db import migrations


def create_default_user_roles(apps, schema_editor):
    UserRole = apps.get_model('usermanagement', 'UserRole')

    # Create 'admin' role if it doesn't exist
    UserRole.objects.get_or_create(
        name='admin',
        defaults={'display_name': 'Admin', 'description': 'Administrator role', 'permissions': {'is_staff': True, 'is_superuser': True}}
    )

    # Create 'customer' role if it doesn't exist
    UserRole.objects.get_or_create(
        name='customer',
        defaults={'display_name': 'Customer', 'description': 'Default customer role'}
    )

class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0004_alter_user_user_role'),
    ]

    operations = [
        migrations.RunPython(create_default_user_roles, reverse_code=migrations.RunPython.noop),
    ]
