# Generated by Django 4.2.13 on 2025-11-06 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0005_alter_user_user_role'),
        ('usermanagement', '0006_ensure_default_roles'),
    ]

    operations = [
    ]
