# Generated by Django 5.2.1 on 2025-09-15 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_delivery_address_order_tracking_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='prescription',
        ),
        migrations.AddField(
            model_name='order',
            name='prescription_image_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='prescription_status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending_review', max_length=20),
        ),
    ]
