# Generated by Django 5.2.1 on 2025-09-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_invoice_invoiceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('payment_completed', 'Payment Completed'), ('prescription_uploaded', 'Prescription Uploaded'), ('verified', 'Verified'), ('prescription_rejected', 'Prescription Rejected'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Aborted', 'Aborted')], default='Pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Refunded', 'Refunded'), ('Aborted', 'Aborted')], max_length=10),
        ),
    ]
