# Generated by Django 5.2.1 on 2025-10-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_order_status_alter_order_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='prescription_image_base64',
        ),
        migrations.AddField(
            model_name='order',
            name='prescription_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
