# Generated by Django 5.2.1 on 2025-10-28 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_order_prescription_image_base64_and_more'),
        ('prescriptions', '0011_remove_prescription_prescriptio_verific_8b0c24_idx_and_more'),
        ('product', '0013_remove_product_composition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='prescription_image_url',
        ),
        migrations.RemoveField(
            model_name='order',
            name='prescription_status',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='order',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='prescriptions.prescription'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.batch'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.product'),
        ),
    ]
