# Generated by Django 4.2.13 on 2025-11-05 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
        ('cart', '0003_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_unit',
            field=models.ForeignKey(blank=True, help_text="The unit in which this product is added to the cart (e.g., 'strip', 'bottle').", null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productunit'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'product_unit')},
        ),
    ]
