import os
import sys
import django
import openpyxl
from datetime import date
from decimal import Decimal

# Add the project directory to the Python path
current_dir = os.path.dirname(os.path.abspath(__file__))
backend_dir = os.path.join(current_dir, 'backend')
sys.path.insert(0, backend_dir)
sys.path.insert(0, current_dir)

# Set up Django environment
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'backend.settings')
print(f"Python path: {sys.path}")
print(f"Current directory: {current_dir}")
print(f"Backend directory: {backend_dir}")

django.setup()

print("Django environment initialized successfully")

from django.contrib.auth import get_user_model
from product.models import Product, Composition, GenericName, Category, ProductComposition, Batch

User = get_user_model()

def create_superuser():
    """Create a superuser if it doesn't exist"""
    try:
        User.objects.get(username='admin')
        print("Superuser already exists")
    except User.DoesNotExist:
        User.objects.create_superuser('admin', 'admin@example.com', 'admin123')
        print("Superuser created successfully")

def insert_product_data(products_data):
    # Get the first available user as the default user
    try:
        default_user = User.objects.first()
        if not default_user:
            print("Error: No users found in the database. Please create a user first.")
            return
    except User.DoesNotExist:
        print("Error: No users found in the database. Please create a user first.")
        return

    for row_data in products_data:
        print(f"Processing product: {row_data.get('product_name')}")

        # Get or create GenericName
        generic_name_obj, _ = GenericName.objects.get_or_create(
            name=row_data['generic_name'],
            defaults={'description': f"Generic name for {row_data['generic_name']}"}
        )

        # Get or create Category
        category_obj, _ = Category.objects.get_or_create(
            name=row_data['category_name'],
            defaults={'description': f"Category for {row_data['category_name']}"}
        )

        # Get or create Composition
        composition_obj, _ = Composition.objects.get_or_create(
            name=row_data['composition_name'],
            defaults={
                'description': f"Composition: {row_data['composition_name']}",
                'created_by': default_user
            }
        )

        # Create or update Product
        product_defaults = {
            'brand_name': row_data['brand_name'],
            'generic_name': generic_name_obj,
            'manufacturer': row_data['manufacturer'],
            'medicine_type': row_data['medicine_type'],
            'prescription_type': row_data['prescription_type'],
            'strength': row_data['strength'],
            'form': row_data['form'],
            'min_stock_level': int(row_data['min_stock_level']),
            'dosage_form': row_data['dosage_form'],
            'pack_size': row_data['pack_size'],
            'packaging_unit': row_data['packaging_unit'],
            'description': row_data['description'],
            'uses': row_data['uses'],
            'side_effects': row_data['side_effects'],
            'how_to_use': row_data['how_to_use'],
            'precautions': row_data['precautions'],
            'storage': row_data['storage'],
            'image_url': row_data['image_url'],
            'hsn_code': row_data['hsn_code'],
            'category': category_obj,
            'is_featured': row_data['is_featured'].lower() == 'true',
            'is_prescription_required': row_data['prescription_type'].lower() == 'rx', # Assuming 'rx' means prescription required
            'created_by': default_user,
        }
        
        product, created = Product.objects.update_or_create(
            name=row_data['product_name'],
            manufacturer=row_data['manufacturer'],
            dosage_form=row_data['dosage_form'],
            defaults=product_defaults
        )

        if created:
            print(f"Created new product: {product.name}")
        else:
            print(f"Updated existing product: {product.name}")

        # Create ProductComposition
        ProductComposition.objects.update_or_create(
            product=product,
            composition=composition_obj,
            defaults={
                'strength': row_data['composition_strength'],
                'unit': row_data['composition_unit'],
                'percentage': Decimal(row_data['composition_percentage']),
                'is_primary': row_data['composition_is_primary'].lower() == 'true',
            }
        )

        # Create Batch
        Batch.objects.update_or_create(
            product=product,
            batch_number=row_data['batch_number'],
            defaults={
                'manufacturing_date': row_data['manufacturing_date'],
                'expiry_date': row_data['expiry_date'],
                'quantity': int(row_data['quantity']),
                'current_quantity': int(row_data['quantity']), # Initial current_quantity is full quantity
                'mrp_price': Decimal(row_data['mrp_price']),
                'discount_percentage': Decimal(row_data['discount_percentage']),
                'selling_price': Decimal(row_data['mrp_price']) * (1 - Decimal(row_data['discount_percentage']) / 100), # Calculated in save method, but good to set a default
                'online_mrp_price': Decimal(row_data['mrp_price']), # Assuming same as mrp_price for now
                'online_discount_percentage': Decimal(row_data['discount_percentage']), # Assuming same for now
                'online_selling_price': Decimal(row_data['mrp_price']) * (1 - Decimal(row_data['discount_percentage']) / 100), # Assuming same for now
                'offline_mrp_price': Decimal(row_data['mrp_price']), # Assuming same for now
                'offline_discount_percentage': Decimal(row_data['discount_percentage']), # Assuming same for now
                'offline_selling_price': Decimal(row_data['mrp_price']) * (1 - Decimal(row_data['discount_percentage']) / 100), # Assuming same for now
            }
        )
        print(f"Successfully processed product: {product.name} with batch {row_data['batch_number']}")

    print("\nData insertion complete.")

if __name__ == "__main__":
    print("Starting database seeding process...")
    
    # Create superuser first
    create_superuser()
    
    print("Starting product data insertion...")
    products_to_insert = [
        # Products from images
        {
            'product_name': 'IndiNature Ayurvedic Hair Oil Ideal For Men & Women | 100% Ayurvedic Medicinal Oil for Hair Strength & Shine | Power of 27 Ingredients With Bhringraj, Neem, Amla & Coconut Oil | Chemical-Free | 100 ml (I)',
            'brand_name': 'IndiNature',
            'generic_name': 'Ayurvedic Hair Oil',
            'manufacturer': 'IndiNature Labs',
            'medicine_type': 'Ayurvedic',
            'prescription_type': 'OTC',
            'strength': '100 ml',
            'form': 'Oil',
            'min_stock_level': 5,
            'dosage_form': 'Topical',
            'pack_size': '1',
            'packaging_unit': 'Bottle',
            'description': '100% Ayurvedic Medicinal Oil for Hair Strength & Shine. Power of 27 Ingredients With Bhringraj, Neem, Amla & Coconut Oil. Chemical-Free.',
            'uses': 'Hair strength, shine, and scalp nourishment.',
            'side_effects': 'None reported.',
            'how_to_use': 'Apply to scalp and hair, massage gently.',
            'precautions': 'For external use only.',
            'storage': 'Store in a cool, dry place.',
            'image_url': 'https://example.com/indinature_hair_oil.jpg',
            'hsn_code': '33059090',
            'category_name': 'Hair Care',
            'is_featured': 'true',
            'composition_name': 'Bhringraj, Neem, Amla, Coconut Oil',
            'composition_strength': 'N/A',
            'composition_unit': 'N/A',
            'composition_percentage': '100.0',
            'composition_is_primary': 'true',
            'batch_number': 'INH001',
            'manufacturing_date': date(2023, 1, 1),
            'expiry_date': date(2025, 12, 31),
            'quantity': 15,
            'mrp_price': '290.00',
            'discount_percentage': '0.0',
        },
        {
            'product_name': 'Ayurvedic Cleanser/Shampoo | Best For Dandruff & Lice Control | Power of 6 Ingredients - Reetha, Neem & Bhringraj | Shampoo for Men & Women | All Hair Types, 200 ml (I)',
            'brand_name': 'VedaMe',
            'generic_name': 'Ayurvedic Shampoo',
            'manufacturer': 'VedaMe Organics',
            'medicine_type': 'Ayurvedic',
            'prescription_type': 'OTC',
            'strength': '200 ml',
            'form': 'Liquid',
            'min_stock_level': 5,
            'dosage_form': 'Topical',
            'pack_size': '1',
            'packaging_unit': 'Bottle',
            'description': 'Best For Dandruff & Lice Control. Power of 6 Ingredients - Reetha, Neem & Bhringraj. Shampoo for Men & Women. All Hair Types.',
            'uses': 'Dandruff control, lice prevention, hair cleansing.',
            'side_effects': 'None reported.',
            'how_to_use': 'Apply to wet hair, lather, rinse thoroughly.',
            'precautions': 'Avoid contact with eyes.',
            'storage': 'Store in a cool, dry place.',
            'image_url': 'https://example.com/vedame_shampoo.jpg',
            'hsn_code': '33051090',
            'category_name': 'Hair Care',
            'is_featured': 'true',
            'composition_name': 'Reetha, Neem, Bhringraj',
            'composition_strength': 'N/A',
            'composition_unit': 'N/A',
            'composition_percentage': '100.0',
            'composition_is_primary': 'true',
            'batch_number': 'VMS002',
            'manufacturing_date': date(2023, 2, 1),
            'expiry_date': date(2025, 11, 30),
            'quantity': 15,
            'mrp_price': '290.00',
            'discount_percentage': '0.0',
        },
        {
            'product_name': 'Pain Relief Oil Roll-On (2*50ml) 100 ml | Powerful Ayurvedic Ingredients for Joint, Muscle, Knee & Back Pain | Fast-Absorbing, Cooling Relief for Shoulder & Arthritis Pain | FDA Approved | Value Pack (Pack of 2)',
            'brand_name': 'Regain',
            'generic_name': 'Pain Relief Oil',
            'manufacturer': 'Regain Pharma',
            'medicine_type': 'Ayurvedic',
            'prescription_type': 'OTC',
            'strength': '100 ml (2x50ml)',
            'form': 'Oil',
            'min_stock_level': 5,
            'dosage_form': 'Topical',
            'pack_size': '2',
            'packaging_unit': 'Roll-On Bottle',
            'description': 'Powerful Ayurvedic Ingredients for Joint, Muscle, Knee & Back Pain. Fast-Absorbing, Cooling Relief for Shoulder & Arthritis Pain. FDA Approved. Value Pack (Pack of 2).',
            'uses': 'Relief from joint pain, muscle pain, back pain, arthritis.',
            'side_effects': 'None reported.',
            'how_to_use': 'Roll on affected area, massage gently.',
            'precautions': 'For external use only. Do not apply on broken skin.',
            'storage': 'Store in a cool, dry place.',
            'image_url': 'https://example.com/regain_pain_oil.jpg',
            'hsn_code': '30049011',
            'category_name': 'Pain Relief',
            'is_featured': 'true',
            'composition_name': 'Menthol, Camphor, Eucalyptus Oil',
            'composition_strength': 'N/A',
            'composition_unit': 'N/A',
            'composition_percentage': '100.0',
            'composition_is_primary': 'true',
            'batch_number': 'RPO003',
            'manufacturing_date': date(2023, 3, 1),
            'expiry_date': date(2025, 10, 31),
            'quantity': 15,
            'mrp_price': '458.00',
            'discount_percentage': '0.0',
        },
        {
            'product_name': 'NutraCeutical Hair Supplement | Power of 34 Ingredients with Biotin, Beet Root, Amla, Grape Seed Extract | For Stronger Hair, Boosts Growth, Nourishes Scalp | 30 Tablets | 100% Vegan (1)',
            'brand_name': 'NutraCeutical',
            'generic_name': 'Hair Supplement',
            'manufacturer': 'NutraCeutical Health',
            'medicine_type': 'Nutraceutical',
            'prescription_type': 'OTC',
            'strength': '30 Tablets',
            'form': 'Tablet',
            'min_stock_level': 5,
            'dosage_form': 'Oral',
            'pack_size': '1',
            'packaging_unit': 'Bottle',
            'description': 'Power of 34 Ingredients with Biotin, Beet Root, Amla, Grape Seed Extract. For Stronger Hair, Boosts Growth, Nourishes Scalp. 30 Tablets. 100% Vegan.',
            'uses': 'Hair growth, hair strength, scalp nourishment.',
            'side_effects': 'None reported.',
            'how_to_use': 'Take one tablet daily after meals.',
            'precautions': 'Consult physician if pregnant or lactating.',
            'storage': 'Store in a cool, dry place.',
            'image_url': 'https://example.com/nutraceutical_hair_supplement.jpg',
            'hsn_code': '21069099',
            'category_name': 'Supplements',
            'is_featured': 'true',
            'composition_name': 'Biotin, Beet Root, Amla, Grape Seed Extract',
            'composition_strength': 'N/A',
            'composition_unit': 'N/A',
            'composition_percentage': '100.0',
            'composition_is_primary': 'true',
            'batch_number': 'NHS004',
            'manufacturing_date': date(2023, 4, 1),
            'expiry_date': date(2025, 9, 30),
            'quantity': 15,
            'mrp_price': '395.00',
            'discount_percentage': '0.0',
        },
        # Additional 15 generic products
        {
            'product_name': 'Generic Pain Reliever 1',
            'brand_name': 'Generic Pharma',
            'generic_name': 'Pain Reliever',
            'manufacturer': 'Generic Meds Inc.',
            'medicine_type': 'Allopathic',
            'prescription_type': 'OTC',
            'strength': '500 mg',
            'form': 'Tablet',
            'min_stock_level': 5,
            'dosage_form': 'Oral',
            'pack_size': '10',
            'packaging_unit': 'Strip',
            'description': 'Fast-acting pain relief for headaches and body aches.',
            'uses': 'Relief from mild to moderate pain.',
            'side_effects': 'May cause drowsiness.',
            'how_to_use': 'Take one tablet with water every 4-6 hours.',
            'precautions': 'Do not exceed recommended dosage.',
            'storage': 'Store in a cool, dry place.',
            'image_url': 'https://example.com/generic_pain_reliever1.jpg',
            'hsn_code': '30049099',
            'category_name': 'Pain Relief',
            'is_featured': 'false',
            'composition_name': 'Paracetamol',
            'composition_strength': '500',
            'composition_unit': 'mg',
            'composition_percentage': '100.0',
            'composition_is_primary': 'true',
            'batch_number': 'GPR001',
            'manufacturing_date': date(2023, 5, 1),
            'expiry_date': date(2025, 8, 31),
            'quantity': 15,
            'mrp_price': '25.00',
            'discount_percentage': '0.0',
        },
        {
            'product_name': 'Generic Cough Syrup 2',
            'brand_name': 'Health Aid',
            'generic_name': 'Cough Suppressant',
            'manufacturer': 'Health Aid Pharma',
            'medicine_type': 'Allopathic',
            'prescription_type': 'OTC',
            'strength': '100 ml',
            'form': 'Syrup',
            'min_stock_level': 5,
            'dosage_form': 'Oral',
            'pack_size': '1',
            'packaging_unit': 'Bottle',
            'description': 'Effective relief from dry cough and throat irritation.',
            'uses': 'Suppresses cough, soothes throat.',
            'side_effects': 'May cause drowsiness.',
            'how_to_use': 'Take 10ml three times a day.',
            'precautions': 'Consult doctor if cough persists.',
            'storage': 'Store in a cool, dry place.',
            'image_url': 'https://example.com/generic_cough_syrup2.jpg',
            'hsn_code': '30049087',
            'category_name': 'Cough & Cold',
            'is_featured': 'false',
            'composition_name': 'Dextromethorphan',
            'composition_strength': '15',
            'composition_unit': 'mg/5ml',
            'composition_percentage': '100.0',
            'composition_is_primary': 'true',
            'batch_number': 'GCS002',
            'manufacturing_date': date(2023, 6, 1),
            'expiry_date': date(2025, 7, 31),
            'quantity': 15,
            'mrp_price': '80.00',
            'discount_percentage': '0.0',
        },
        {
            'product_name': 'Generic Antacid Liquid 3',
            'brand_name': 'Stomach Soothe',
            'generic_name': 'Antacid',
            'manufacturer': 'Stomach Soothe Labs',
            'medicine_type': 'Allopathic',
            'prescription_type': 'OTC',
            'strength': '200 ml',
            'form': 'Liquid',
            'min_stock_level': 5,
            'dosage_form': 'Oral',
            'pack_size': '1',
            'packaging_unit': 'Bottle',
            'description': 'Quick relief from acidity and heartburn.',
            'uses': 'Relief from indigestion, heartburn, and sour stomach.',
            'side_effects': 'May cause constipation.',
            'how_to_use': 'Take 10ml after meals or as directed by physician.',
            'precautions': 'Shake well before use.',
            'storage': 'Store in a cool, dry place.',
            'image_url': 'https://example.com/generic_antacid_liquid3.jpg',
            'hsn_code': '30049079',
            'category_name': 'Digestive Health',
            'is_featured': 'false',
            'composition_name': 'Magnesium Hydroxide, Aluminum Hydroxide',
            'composition_strength': 'N/A',
            'composition_unit': 'N/A',
            'composition_percentage': '100.0',
            'composition_is_primary': 'true',
            'batch_number': 'GAL003',
            'manufacturing_date': date(2023, 7, 1),
            'expiry_date': date(2025, 6, 30),
            'quantity': 15,
            'mrp_price': '120.00',
            'discount_percentage': '0.0',
        },
        {
            'product_name': 'Generic Multivitamin Tablet 4',
            'brand_name': 'VitaBoost',
            'generic_name': 'Multivitamin',
            'manufacturer': 'VitaBoost Health',
            'medicine_type': 'Nutraceutical',
            'prescription_type': 'OTC',
            'strength': '30 Tablets',
            'form': 'Tablet',
            'min_stock_level': 5,
            'dosage_form': 'Oral',
            'pack_size': '1',
            'packaging_unit': 'Bottle',
            'description': 'Daily supplement for overall health and well-being.',
            'uses': 'Dietary supplement, boosts immunity.',
            'side_effects': 'None reported.',
            'how_to_use': 'Take one tablet daily after meals.',
            'precautions': 'Do not exceed recommended dosage.',
            'storage': 'Store in a cool, dry place.',
            'image_url': 'https://example.com/generic_multivitamin_tablet4.jpg',
            'hsn_code': '21069099',
            'category_name': 'Supplements',
            'is_featured': 'false',
            'composition_name': 'Vitamins A, B, C, D, E, Zinc',
            'composition_strength': 'N/A',
            'composition_unit': 'N/A',
            'composition_percentage': '100.0',
            'composition_is_primary': 'true',
            'batch_number': 'GMT004',
            'manufacturing_date': date(2023, 8, 1),
            'expiry_date': date(2025, 5, 31),
            'quantity': 15,
            'mrp_price': '180.00',
            'discount_percentage': '0.0',
        },
        {
            'product_name': 'Generic Antiseptic Cream 5',
            'brand_name': 'HealFast',
            'generic_name': 'Antiseptic',
            'manufacturer': 'HealFast Solutions',
            'medicine_type': 'Allopathic',
            'prescription_type': 'OTC',
            'strength': '20 gm',
            'form': 'Cream',
            'min_stock_level': 5,
            'dosage_form': 'Topical',
            'pack_size': '1',
            'packaging_unit': 'Tube',
            'description': 'For cuts, wounds, and minor skin infections.',
            'uses': 'Antiseptic for minor cuts and wounds.',
            'side_effects': 'May cause mild irritation.',
            'how_to_use': 'Apply a thin layer on the affected area twice daily.',
            'precautions': 'For external use only.',
            'storage': 'Store in a cool, dry place.',
            'image_url': 'https://example.com/generic_antiseptic_cream5.jpg',
            'hsn_code': '30049069',
            'category_name': 'First Aid',
            'is_featured': 'false',
            'composition_name': 'Povidone-iodine',
            'composition_strength': '10',
            'composition_unit': '%',
            'composition_percentage': '100.0',
            'composition_is_primary': 'true',
            'batch_number': 'GAC005',
            'manufacturing_date': date(2023, 9, 1),
            'expiry_date': date(2025, 4, 30),
            'quantity': 15,
            'mrp_price': '50.00',
            'discount_percentage': '0.0',
        },
        {
            'product_name': 'Generic Eye Drops 6',
            'brand_name': 'ClearSight',
            'generic_name': 'Eye Drops',
            'manufacturer': 'ClearSight Pharma',
            'medicine_type': 'Allopathic',
            'prescription_type': 'OTC',
            'strength': '10 ml',
            'form': 'Liquid',
            'min_stock_level': 5,
            'dosage_form': 'Ophthalmic',
            'pack_size': '1',
            'packaging_unit': 'Bottle',
            'description': 'Relieves dry eyes and irritation.',
            'uses': 'Lubricates and moisturizes eyes.',
            'side_effects': 'Temporary blurring of vision.',
            'how_to_use': 'Instill 1-2 drops in each eye as needed.',
            'precautions': 'Do not touch dropper tip to any surface.',
            'storage': 'Store in a cool, dry place.',
            'image_url': 'https://example.com/generic_eye_drops6.jpg',
            'hsn_code': '30049059',
            'category_name': 'Eye Care',
            'is_featured': 'false',
            'composition_name': 'Carboxymethylcellulose',
            'composition_strength': '0.5',
            'composition_unit': '%',
            'composition_percentage': '100.0',
            'composition_is_primary': 'true',
            'batch_number': 'GED006',
            'manufacturing_date': date(2023, 10, 1),
            'expiry_date': date(2025, 3, 31),
            'quantity': 15,
            'mrp_price': '90.00',
            'discount_percentage': '0.0',
        },
        {
            'product_name': 'Generic Nasal Spray 7',
            'brand_name': 'BreatheEasy',
            'generic_name': 'Nasal Decongestant',
            'manufacturer': 'BreatheEasy Solutions',
            'medicine_type': 'Allopathic',
            'prescription_type': 'OTC',
            'strength': '10 ml',
            'form': 'Spray',
            'min_stock_level': 5,
            'dosage_form': 'Nasal',
            'pack_size': '1',
            'packaging_unit': 'Bottle',
            'description': 'Relieves nasal congestion due to colds or allergies.',
            'uses': 'Nasal decongestion.',
            'side_effects': 'Temporary burning, stinging, dryness in the nose.',
            'how_to_use': 'Spray once or twice in each nostril every 10-12 hours.',
            'precautions': 'Do not use for more than 3 days.',
            'storage': 'Store in a cool, dry place.',
            'image_url': 'https://example.com/generic_nasal_spray7.jpg',
            'hsn_code': '30049049',
            'category_name': 'Cough & Cold',
            'is_featured': 'false',
            'composition_name': 'Oxymetazoline',
            'composition_strength': '0.05',
            'composition_unit': '%',
            'composition_percentage': '100.0',
            'composition_is_primary': 'true',
            'batch_number': 'GNS007',
            'manufacturing_date': date(2023, 11, 1),
            'expiry_date': date(2025, 2, 28),
            'quantity': 15,
            'mrp_price': '70.00',
            'discount_percentage': '0.0',
        },
        {
            'product_name': 'Generic Oral Rehydration Salts 8',
            'brand_name': 'Rehydrate',
            'generic_name': 'ORS',
            'manufacturer': 'Rehydrate Solutions',
            'medicine_type': 'Allopathic',
            'prescription_type': 'OTC',
            'strength': '21.8 gm',
            'form': 'Powder',
            'min_stock_level': 5,
            'dosage_form': 'Oral',
            'pack_size': '1',
            'packaging_unit': 'Sachet',
            'description': 'Restores body fluids and electrolytes lost due to dehydration.',
            'uses': 'Treatment of dehydration.',
            'side_effects': 'None reported.',
            'how_to_use': 'Mix contents of sachet in 1 liter of water and consume.',
            'precautions': 'Use with caution in patients with kidney problems.',
            'storage': 'Store in a cool, dry place.',
            'image_url': 'https://example.com/generic_ors8.jpg',
            'hsn_code': '30049039',
            'category_name': 'Digestive Health',
            'is_featured': 'false',
            'composition_name': 'Sodium Chloride, Potassium Chloride, Glucose',
            'composition_strength': 'N/A',
            'composition_unit': 'N/A',
            'composition_percentage': '100.0',
            'composition_is_primary': 'true',
            'batch_number': 'GORS008',
            'manufacturing_date': date(2023, 12, 1),
            'expiry_date': date(2025, 1, 31),
            'quantity': 15,
            'mrp_price': '20.00',
            'discount_percentage': '0.0',
        },
        {
            'product_name': 'Generic Vitamin C Tablet 9',
            'brand_name': 'ImmunoBoost',
            'generic_name': 'Vitamin C',
            'manufacturer': 'ImmunoBoost Health',
            'medicine_type': 'Nutraceutical',
            'prescription_type': 'OTC',
            'strength': '500 mg',
            'form': 'Tablet',
            'min_stock_level': 5,
            'dosage_form': 'Oral',
            'pack_size': '10',
            'packaging_unit': 'Strip',
            'description': 'Boosts immunity and acts as an antioxidant.',
            'uses': 'Immunity booster, antioxidant.',
            'side_effects': 'None reported.',
            'how_to_use': 'Take one tablet daily after meals.',
            'precautions': 'Do not exceed recommended dosage.',
            'storage': 'Store in a cool, dry place.',
            'image_url': 'https://example.com/generic_vitamin_c9.jpg',
            'hsn_code': '21069099',
            'category_name': 'Supplements',
            'is_featured': 'false',
            'composition_name': 'Ascorbic Acid',
            'composition_strength': '500',
            'composition_unit': 'mg',
            'composition_percentage': '100.0',
            'composition_is_primary': 'true',
            'batch_number': 'GVCT009',
            'manufacturing_date': date(2024, 1, 1),
            'expiry_date': date(2026, 12, 31),
            'quantity': 15,
            'mrp_price': '40.00',
            'discount_percentage': '0.0',
        },
        {
            'product_name': 'Generic Hand Sanitizer 10',
            'brand_name': 'CleanHands',
            'generic_name': 'Hand Sanitizer',
            'manufacturer': 'CleanHands Hygiene',
            'medicine_type': 'General',
            'prescription_type': 'OTC',
            'strength': '100 ml',
            'form': 'Gel',
            'min_stock_level': 5,
            'dosage_form': 'Topical',
            'pack_size': '1',
            'packaging_unit': 'Bottle',
            'description': 'Kills 99.9% of germs without water.',
            'uses': 'Hand hygiene.',
            'side_effects': 'May cause skin dryness.',
            'how_to_use': 'Apply a small amount to palms and rub thoroughly.',
            'precautions': 'Flammable. Keep away from fire.',
            'storage': 'Store in a cool, dry place.',
            'image_url': 'https://example.com/generic_hand_sanitizer10.jpg',
            'hsn_code': '34022090',
            'category_name': 'Hygiene',
            'is_featured': 'false',
            'composition_name': 'Ethyl Alcohol',
            'composition_strength': '70',
            'composition_unit': '%',
            'composition_percentage': '100.0',
            'composition_is_primary': 'true',
            'batch_number': 'GHS010',
            'manufacturing_date': date(2024, 2, 1),
            'expiry_date': date(2026, 11, 30),
            'quantity': 15,
            'mrp_price': '60.00',
            'discount_percentage': '0.0',
        },
        {
            'product_name': 'Generic Pain Balm 11',
            'brand_name': 'Relief Balm',
            'generic_name': 'Pain Balm',
            'manufacturer': 'Relief Pharma',
            'medicine_type': 'Ayurvedic',
            'prescription_type': 'OTC',
            'strength': '25 gm',
            'form': 'Balm',
            'min_stock_level': 5,
            'dosage_form': 'Topical',
            'pack_size': '1',
            'packaging_unit': 'Jar',
            'description': 'Provides quick relief from headaches and body pains.',
            'uses': 'Relief from headaches, muscle pain, joint pain.',
            'side_effects': 'May cause mild irritation.',
            'how_to_use': 'Apply on affected area and gently massage.',
            'precautions': 'For external use only.',
            'storage': 'Store in a cool, dry place.',
            'image_url': 'https://example.com/generic_pain_balm11.jpg',
            'hsn_code': '30049011',
            'category_name': 'Pain Relief',
            'is_featured': 'false',
            'composition_name': 'Menthol, Camphor, Wintergreen Oil',
            'composition_strength': 'N/A',
            'composition_unit': 'N/A',
            'composition_percentage': '100.0',
            'composition_is_primary': 'true',
            'batch_number': 'GPB011',
            'manufacturing_date': date(2024, 3, 1),
            'expiry_date': date(2026, 10, 31),
            'quantity': 15,
            'mrp_price': '35.00',
            'discount_percentage': '0.0',
        },
        {
            'product_name': 'Generic Digestive Enzyme 12',
            'brand_name': 'DigestiCare',
            'generic_name': 'Digestive Enzyme',
            'manufacturer': 'DigestiCare Health',
            'medicine_type': 'Nutraceutical',
            'prescription_type': 'OTC',
            'strength': '10 Tablets',
            'form': 'Tablet',
            'min_stock_level': 5,
            'dosage_form': 'Oral',
            'pack_size': '1',
            'packaging_unit': 'Strip',
            'description': 'Aids in digestion and reduces bloating.',
            'uses': 'Improves digestion, reduces bloating and gas.',
            'side_effects': 'None reported.',
            'how_to_use': 'Take one tablet after heavy meals.',
            'precautions': 'Consult physician if pregnant or lactating.',
            'storage': 'Store in a cool, dry place.',
            'image_url': 'https://example.com/generic_digestive_enzyme12.jpg',
            'hsn_code': '21069099',
            'category_name': 'Digestive Health',
            'is_featured': 'false',
            'composition_name': 'Papain, Fungal Diastase',
            'composition_strength': 'N/A',
            'composition_unit': 'N/A',
            'composition_percentage': '100.0',
            'composition_is_primary': 'true',
            'batch_number': 'GDE012',
            'manufacturing_date': date(2024, 4, 1),
            'expiry_date': date(2026, 9, 30),
            'quantity': 15,
            'mrp_price': '75.00',
            'discount_percentage': '0.0',
        },
        {
            'product_name': 'Generic Calcium Supplement 13',
            'brand_name': 'BoneStrong',
            'generic_name': 'Calcium',
            'manufacturer': 'BoneStrong Health',
            'medicine_type': 'Nutraceutical',
            'prescription_type': 'OTC',
            'strength': '30 Tablets',
            'form': 'Tablet',
            'min_stock_level': 5,
            'dosage_form': 'Oral',
            'pack_size': '1',
            'packaging_unit': 'Bottle',
            'description': 'Supports strong bones and teeth.',
            'uses': 'Bone health, prevents osteoporosis.',
            'side_effects': 'None reported.',
            'how_to_use': 'Take one tablet daily with food.',
            'precautions': 'Consult physician if you have kidney stones.',
            'storage': 'Store in a cool, dry place.',
            'image_url': 'https://example.com/generic_calcium_supplement13.jpg',
            'hsn_code': '21069099',
            'category_name': 'Supplements',
            'is_featured': 'false',
            'composition_name': 'Calcium Carbonate, Vitamin D3',
            'composition_strength': 'N/A',
            'composition_unit': 'N/A',
            'composition_percentage': '100.0',
            'composition_is_primary': 'true',
            'batch_number': 'GCS013',
            'manufacturing_date': date(2024, 5, 1),
            'expiry_date': date(2026, 8, 31),
            'quantity': 15,
            'mrp_price': '150.00',
            'discount_percentage': '0.0',
        },
        {
            'product_name': 'Generic Moisturizing Lotion 14',
            'brand_name': 'SoftSkin',
            'generic_name': 'Moisturizer',
            'manufacturer': 'SoftSkin Care',
            'medicine_type': 'Cosmetic',
            'prescription_type': 'OTC',
            'strength': '100 ml',
            'form': 'Lotion',
            'min_stock_level': 5,
            'dosage_form': 'Topical',
            'pack_size': '1',
            'packaging_unit': 'Bottle',
            'description': 'Keeps skin hydrated and soft all day long.',
            'uses': 'Moisturizes dry skin.',
            'side_effects': 'None reported.',
            'how_to_use': 'Apply generously on body after bath.',
            'precautions': 'For external use only.',
            'storage': 'Store in a cool, dry place.',
            'image_url': 'https://example.com/generic_moisturizing_lotion14.jpg',
            'hsn_code': '33049990',
            'category_name': 'Skin Care',
            'is_featured': 'false',
            'composition_name': 'Glycerin, Shea Butter',
            'composition_strength': 'N/A',
            'composition_unit': 'N/A',
            'composition_percentage': '100.0',
            'composition_is_primary': 'true',
            'batch_number': 'GML014',
            'manufacturing_date': date(2024, 6, 1),
            'expiry_date': date(2026, 7, 31),
            'quantity': 15,
            'mrp_price': '110.00',
            'discount_percentage': '0.0',
        },
        {
            'product_name': 'Generic Sunscreen Lotion 15',
            'brand_name': 'SunShield',
            'generic_name': 'Sunscreen',
            'manufacturer': 'SunShield Protection',
            'medicine_type': 'Cosmetic',
            'prescription_type': 'OTC',
            'strength': '50 gm',
            'form': 'Lotion',
            'min_stock_level': 5,
            'dosage_form': 'Topical',
            'pack_size': '1',
            'packaging_unit': 'Tube',
            'description': 'SPF 50+ protection against harmful UV rays.',
            'uses': 'Sun protection.',
            'side_effects': 'None reported.',
            'how_to_use': 'Apply liberally 15 minutes before sun exposure.',
            'precautions': 'Reapply every 2 hours.',
            'storage': 'Store in a cool, dry place.',
            'image_url': 'https://example.com/generic_sunscreen_lotion15.jpg',
            'hsn_code': '33049930',
            'category_name': 'Skin Care',
            'is_featured': 'false',
            'composition_name': 'Zinc Oxide, Titanium Dioxide',
            'composition_strength': 'N/A',
            'composition_unit': 'N/A',
            'composition_percentage': '100.0',
            'composition_is_primary': 'true',
            'batch_number': 'GSL015',
            'manufacturing_date': date(2024, 7, 1),
            'expiry_date': date(2026, 6, 30),
            'quantity': 15,
            'mrp_price': '200.00',
            'discount_percentage': '0.0',
        },
        {
            'product_name': 'Generic Glucose Powder 16',
            'brand_name': 'EnergyBoost',
            'generic_name': 'Glucose',
            'manufacturer': 'EnergyBoost Health',
            'medicine_type': 'Nutraceutical',
            'prescription_type': 'OTC',
            'strength': '100 gm',
            'form': 'Powder',
            'min_stock_level': 5,
            'dosage_form': 'Oral',
            'pack_size': '1',
            'packaging_unit': 'Pouch',
            'description': 'Instant energy source for quick recovery.',
            'uses': 'Energy booster, rehydration.',
            'side_effects': 'None reported.',
            'how_to_use': 'Mix 2 spoons in water and consume.',
            'precautions': 'Diabetics should consult a physician.',
            'storage': 'Store in a cool, dry place.',
            'image_url': 'https://example.com/generic_glucose_powder16.jpg',
            'hsn_code': '17023010',
            'category_name': 'Energy & Fitness',
            'is_featured': 'false',
            'composition_name': 'Dextrose Monohydrate',
            'composition_strength': '100',
            'composition_unit': '%',
            'composition_percentage': '100.0',
            'composition_is_primary': 'true',
            'batch_number': 'GGP016',
            'manufacturing_date': date(2024, 8, 1),
            'expiry_date': date(2026, 5, 31),
            'quantity': 15,
            'mrp_price': '45.00',
            'discount_percentage': '0.0',
        },
        {
            'product_name': 'Generic Protein Powder 17',
            'brand_name': 'MuscleMax',
            'generic_name': 'Protein Supplement',
            'manufacturer': 'MuscleMax Nutrition',
            'medicine_type': 'Nutraceutical',
            'prescription_type': 'OTC',
            'strength': '500 gm',
            'form': 'Powder',
            'min_stock_level': 5,
            'dosage_form': 'Oral',
            'pack_size': '1',
            'packaging_unit': 'Jar',
            'description': 'High-quality protein for muscle growth and recovery.',
            'uses': 'Muscle building, post-workout recovery.',
            'side_effects': 'None reported.',
            'how_to_use': 'Mix 1 scoop with milk or water after workout.',
            'precautions': 'Consult a dietitian before use.',
            'storage': 'Store in a cool, dry place.',
            'image_url': 'https://example.com/generic_protein_powder17.jpg',
            'hsn_code': '21061000',
            'category_name': 'Energy & Fitness',
            'is_featured': 'false',
            'composition_name': 'Whey Protein Concentrate',
            'composition_strength': '80',
            'composition_unit': '%',
            'composition_percentage': '100.0',
            'composition_is_primary': 'true',
            'batch_number': 'GPP017',
            'manufacturing_date': date(2024, 9, 1),
            'expiry_date': date(2026, 4, 30),
            'quantity': 15,
            'mrp_price': '750.00',
            'discount_percentage': '0.0',
        },
        {
            'product_name': 'Generic Immunity Booster 18',
            'brand_name': 'ImmuneShield',
            'generic_name': 'Immunity Booster',
            'manufacturer': 'ImmuneShield Health',
            'medicine_type': 'Ayurvedic',
            'prescription_type': 'OTC',
            'strength': '60 Capsules',
            'form': 'Capsule',
            'min_stock_level': 5,
            'dosage_form': 'Oral',
            'pack_size': '1',
            'packaging_unit': 'Bottle',
            'description': 'Natural ingredients to strengthen your immune system.',
            'uses': 'Boosts immunity, prevents infections.',
            'side_effects': 'None reported.',
            'how_to_use': 'Take one capsule twice daily after meals.',
            'precautions': 'Consult physician if pregnant or lactating.',
            'storage': 'Store in a cool, dry place.',
            'image_url': 'https://example.com/generic_immunity_booster18.jpg',
            'hsn_code': '21069099',
            'category_name': 'Supplements',
            'is_featured': 'false',
            'composition_name': 'Ashwagandha, Giloy, Tulsi',
            'composition_strength': 'N/A',
            'composition_unit': 'N/A',
            'composition_percentage': '100.0',
            'composition_is_primary': 'true',
            'batch_number': 'GIB018',
            'manufacturing_date': date(2024, 10, 1),
            'expiry_date': date(2026, 3, 31),
            'quantity': 15,
            'mrp_price': '300.00',
            'discount_percentage': '0.0',
        },
        {
            'product_name': 'Generic Joint Support 19',
            'brand_name': 'FlexiJoint',
            'generic_name': 'Joint Support',
            'manufacturer': 'FlexiJoint Care',
            'medicine_type': 'Nutraceutical',
            'prescription_type': 'OTC',
            'strength': '60 Capsules',
            'form': 'Capsule',
            'min_stock_level': 5,
            'dosage_form': 'Oral',
            'pack_size': '1',
            'packaging_unit': 'Bottle',
            'description': 'Supports joint health and flexibility.',
            'uses': 'Reduces joint pain, improves flexibility.',
            'side_effects': 'None reported.',
            'how_to_use': 'Take one capsule daily after meals.',
            'precautions': 'Consult physician if you have shellfish allergy.',
            'storage': 'Store in a cool, dry place.',
            'image_url': 'https://example.com/generic_joint_support19.jpg',
            'hsn_code': '21069099',
            'category_name': 'Supplements',
            'is_featured': 'false',
            'composition_name': 'Glucosamine, Chondroitin',
            'composition_strength': 'N/A',
            'composition_unit': 'N/A',
            'composition_percentage': '100.0',
            'composition_is_primary': 'true',
            'batch_number': 'GJS019',
            'manufacturing_date': date(2024, 11, 1),
            'expiry_date': date(2026, 2, 28),
            'quantity': 15,
            'mrp_price': '400.00',
            'discount_percentage': '0.0',
        }
    ]
    insert_product_data(products_to_insert)
