# Generated by Django 5.2.1 on 2025-11-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='ordered_quantity_display',
            field=models.DecimalField(decimal_places=10, default=0, help_text='Quantity as entered by the user in the selected display unit for purchase order.', max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='selected_unit_abbreviation',
            field=models.CharField(blank=True, help_text='Abbreviation of the unit selected by the user.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='selected_unit_name',
            field=models.CharField(blank=True, help_text='Name of the unit selected by the user.', max_length=50),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='moved_quantity_display',
            field=models.DecimalField(decimal_places=10, default=0, help_text='Quantity as entered by the user in the selected display unit for stock movement.', max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='selected_unit_abbreviation',
            field=models.CharField(blank=True, help_text='Abbreviation of the unit selected by the user.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='selected_unit_name',
            field=models.CharField(blank=True, help_text='Name of the unit selected by the user.', max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=10, help_text="Quantity in the product's base unit for stock management.", max_digits=20),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.DecimalField(decimal_places=10, help_text="Quantity in the product's base unit for stock management. Positive for IN, negative for OUT.", max_digits=20),
        ),
    ]
