# Generated by Django 5.2.1 on 2025-10-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_purchaseorderitem_tax_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
