# Generated by Django 5.2.1 on 2025-10-23 01:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_purchaseorderitem_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturn',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='return_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
