# Generated by Django 5.2.1 on 2025-10-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_purchasereturn_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturnitem',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
