# Generated by Django 5.2.1 on 2025-11-01 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_purchasereturnitem_batch_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='free_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
