# Generated by Django 5.2.1 on 2025-11-01 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_purchaseorderitem_free_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='free_quantity',
        ),
    ]
