# Generated by Django 5.2.1 on 2025-11-06 08:59

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('current_quantity', models.DecimalField(decimal_places=10, max_digits=20)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mrp_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('online_mrp_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('online_discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('online_selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('offline_mrp_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('offline_discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('offline_selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_primary', models.BooleanField(default=False)),
                ('mfg_license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('scientific_name', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('side_effects', models.TextField(blank=True)),
                ('contraindications', models.TextField(blank=True)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('therapeutic_class', models.CharField(blank=True, max_length=100)),
                ('mechanism_of_action', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Composition',
                'verbose_name_plural': 'Compositions',
                'db_table': 'compositions',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Discount percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('description', models.TextField(blank=True)),
                ('target_type', models.CharField(choices=[('product', 'Product'), ('category', 'Category')], max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
            },
        ),
        migrations.CreateModel(
            name='GenericName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalBatch',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('current_quantity', models.DecimalField(decimal_places=10, max_digits=20)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mrp_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('online_mrp_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('online_discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('online_selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('offline_mrp_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('offline_discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('offline_selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_primary', models.BooleanField(default=False)),
                ('mfg_license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical batch',
                'verbose_name_plural': 'historical batchs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_on_hand', models.PositiveIntegerField()),
                ('reorder_point', models.PositiveIntegerField()),
                ('last_restock_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand_name', models.CharField(blank=True, max_length=200)),
                ('manufacturer', models.CharField(default='MedCorp', max_length=255)),
                ('medicine_type', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('cream', 'Cream'), ('drops', 'Drops'), ('inhaler', 'Inhaler'), ('other', 'Other')], default='tablet', max_length=20)),
                ('prescription_type', models.CharField(choices=[('otc', 'Over The Counter'), ('prescription', 'Prescription Required'), ('controlled', 'Controlled Substance')], default='otc', max_length=20)),
                ('form', models.CharField(blank=True, max_length=50)),
                ('min_stock_level', models.PositiveIntegerField(default=10)),
                ('dosage_form', models.CharField(blank=True, max_length=100)),
                ('pack_size', models.PositiveIntegerField(default=1, help_text='Number of units in one package (e.g., 10 tablets in a strip)')),
                ('description', models.TextField(blank=True)),
                ('uses', models.TextField(blank=True)),
                ('side_effects', models.TextField(blank=True)),
                ('how_to_use', models.TextField(blank=True)),
                ('precautions', models.TextField(blank=True)),
                ('storage', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('hsn_code', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.DecimalField(blank=True, decimal_places=4, help_text='Strength value (e.g., 500 for 500mg)', max_digits=10, null=True)),
                ('strength_unit', models.CharField(blank=True, help_text="Unit of strength (e.g., 'mg', 'ml')", max_length=50)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Product Composition',
                'verbose_name_plural': 'Product Compositions',
                'db_table': 'product_compositions',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, max_length=200)),
                ('comment', models.TextField(blank=True)),
                ('is_verified_purchase', models.BooleanField(default=False)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#007bff', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTagAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(help_text="e.g., 'Tablet', 'Bottle', 'Strip'", max_length=50)),
                ('unit_abbreviation', models.CharField(blank=True, help_text="e.g., 'tab', 'btl', 'strip'", max_length=10, null=True)),
                ('base_unit_name', models.CharField(help_text="e.g., 'Milligram', 'Milliliter', 'Piece'", max_length=50)),
                ('base_unit_abbreviation', models.CharField(blank=True, help_text="e.g., 'mg', 'mL', 'pc'", max_length=10, null=True)),
                ('conversion_factor', models.DecimalField(decimal_places=10, help_text="Factor to multiply 'unit' quantity to get 'base_unit' quantity. E.g., if 1 strip = 10 tablets, factor is 10.", max_digits=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Unit',
                'verbose_name_plural': 'Product Units',
                'db_table': 'product_units',
            },
        ),
        migrations.CreateModel(
            name='ProductViewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.category')),
            ],
        ),
    ]
