# Generated by Django 5.2.3 on 2025-07-01 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(default='MedCorp', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='generic_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.genericname'),
        ),
    ]
