# Generated by Django 5.2.3 on 2025-07-10 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_producttag_productimage_productviewhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True, help_text='Active ingredients and their quantities'),
        ),
        migrations.AddField(
            model_name='product',
            name='how_to_use',
            field=models.TextField(blank=True, help_text='Dosage and administration instructions'),
        ),
        migrations.AddField(
            model_name='product',
            name='precautions',
            field=models.TextField(blank=True, help_text='Warnings and precautions'),
        ),
        migrations.AddField(
            model_name='product',
            name='side_effects',
            field=models.TextField(blank=True, help_text='Possible side effects'),
        ),
        migrations.AddField(
            model_name='product',
            name='storage',
            field=models.TextField(blank=True, help_text='Storage conditions'),
        ),
        migrations.AddField(
            model_name='product',
            name='uses',
            field=models.TextField(blank=True, help_text='Medical uses and indications'),
        ),
    ]
