# Generated by Django 4.2.13 on 2025-11-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_prescription_required',
        ),
        migrations.AlterField(
            model_name='batch',
            name='current_quantity',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='batch',
            name='quantity',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='historicalbatch',
            name='current_quantity',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='historicalbatch',
            name='quantity',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
    ]
