# Generated by Django 5.2.3 on 2025-07-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pack_size',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
