# Generated by Django 5.2.4 on 2025-08-05 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='aliases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='composition',
            name='mechanism_of_action',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='composition',
            name='therapeutic_class',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='productcomposition',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productcomposition',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productcomposition',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='compositions',
            field=models.ManyToManyField(related_name='product_list', through='product.ProductComposition', to='product.composition'),
        ),
        migrations.AlterField(
            model_name='productcomposition',
            name='composition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composition_products', to='product.composition'),
        ),
        migrations.AlterField(
            model_name='productcomposition',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_compositions', to='product.product'),
        ),
    ]
