# Generated by Django 4.2.13 on 2025-11-06 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_unique_together_product_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcomposition',
            old_name='strength_unit',
            new_name='unit',
        ),
    ]
