# Generated by Django 4.2.13 on 2025-11-07 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_strength_unit_productcomposition_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='packaging_unit',
            field=models.ForeignKey(blank=True, help_text='Defines the packaging unit for this product.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaging_products', to='product.productunit'),
        ),
    ]
