# Generated by Django 5.2.1 on 2025-10-05 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_stock_quantity_alter_product_mrp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='mrp',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
