# Generated by Django 5.2.1 on 2025-11-07 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_packaging_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcomposition',
            old_name='unit',
            new_name='strength_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='packaging_unit',
        ),
    ]
