# Generated by Django 5.2.1 on 2025-10-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_mrp_remove_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Designates this batch as the primary one for display purposes.'),
        ),
    ]
