# Generated by Django 4.2.13 on 2025-11-07 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_unit_productcomposition_strength_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='generic_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.genericname'),
        ),
    ]
