# Generated by Django 5.2.1 on 2025-10-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_batch_is_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='mrp_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
