# Generated by Django 5.2.1 on 2025-10-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_batch_mrp_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
