# Generated by Django 5.2.1 on 2025-10-12 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_batch_discount_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='is_primary',
        ),
    ]
