# Generated by Django 5.2.1 on 2025-10-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_batch_is_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
