# Generated by Django 5.2.1 on 2025-10-19 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='offline_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='batch',
            name='offline_mrp_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='batch',
            name='offline_selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='batch',
            name='online_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='batch',
            name='online_mrp_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='batch',
            name='online_selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
