# Generated by Django 5.2.1 on 2025-10-31 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_batch_tax_percentage_historicalbatch_tax_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_prescription_required',
            field=models.BooleanField(default=False),
        ),
    ]
