# Generated by Django 5.2.1 on 2025-09-19 07:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0005_remove_order_prescription_and_more'),
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TPCServiceableArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=10, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('is_serviceable', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TPC Serviceable Area',
                'verbose_name_plural': 'TPC Serviceable Areas',
            },
        ),
        migrations.CreateModel(
            name='CourierShipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(max_length=100, unique=True)),
                ('tpc_order_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Pickup'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('cancelled', 'Cancelled'), ('exception', 'Exception')], default='pending', max_length=20)),
                ('current_location', models.CharField(blank=True, max_length=255)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery', models.DateTimeField(blank=True, null=True)),
                ('pickup_scheduled', models.DateTimeField(blank=True, null=True)),
                ('pickup_completed', models.DateTimeField(blank=True, null=True)),
                ('pickup_address', models.JSONField(default=dict)),
                ('delivery_address', models.JSONField(default=dict)),
                ('delivery_instructions', models.TextField(blank=True)),
                ('delivery_contact', models.CharField(max_length=15)),
                ('weight', models.DecimalField(decimal_places=2, default=0.5, max_digits=8)),
                ('dimensions', models.JSONField(default=dict)),
                ('declared_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_charges', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cod_charges', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_charges', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tpc_response', models.JSONField(default=dict)),
                ('tracking_history', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courier_shipment', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='TPCRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=255, verbose_name='Recipient Name')),
                ('recipient_company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Recipient Company')),
                ('recipient_mobile', models.CharField(max_length=20, verbose_name='Recipient Mobile')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Recipient Email')),
                ('recipient_gstin', models.CharField(blank=True, max_length=20, null=True, verbose_name='Recipient GSTIN')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tpc_recipients', to='usermanagement.address')),
            ],
        ),
    ]
