# Generated by Django 5.2.4 on 2025-08-05 06:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_orderstatushistory_ordertracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('courier_type', models.CharField(choices=[('delhivery', 'Delhivery'), ('bluedart', 'Blue Dart'), ('dtdc', 'DTDC'), ('fedex', 'FedEx'), ('aramex', 'Aramex'), ('ecom', 'Ecom Express'), ('xpressbees', 'XpressBees'), ('professional', 'Professional Courier')], max_length=20)),
                ('api_endpoint', models.URLField()),
                ('api_key', models.CharField(max_length=255)),
                ('api_secret', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('service_areas', models.JSONField(default=list)),
                ('pricing_config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourierRateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=20)),
                ('weight_slab_start', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight_slab_end', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rate_per_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('minimum_charge', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cod_percentage', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('fuel_surcharge_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('courier_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courier.courierpartner')),
            ],
        ),
        migrations.CreateModel(
            name='CourierShipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(max_length=100, unique=True)),
                ('courier_order_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Pickup'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('cancelled', 'Cancelled'), ('exception', 'Exception')], default='pending', max_length=20)),
                ('current_location', models.CharField(blank=True, max_length=255)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery', models.DateTimeField(blank=True, null=True)),
                ('pickup_scheduled', models.DateTimeField(blank=True, null=True)),
                ('pickup_completed', models.DateTimeField(blank=True, null=True)),
                ('pickup_address', models.JSONField(default=dict)),
                ('delivery_address', models.JSONField(default=dict)),
                ('delivery_instructions', models.TextField(blank=True)),
                ('delivery_contact', models.CharField(max_length=15)),
                ('weight', models.DecimalField(decimal_places=2, default=0.5, max_digits=8)),
                ('dimensions', models.JSONField(default=dict)),
                ('declared_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_charges', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cod_charges', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_charges', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('courier_response', models.JSONField(default=dict)),
                ('tracking_history', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courier_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courier.courierpartner')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courier_shipment', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='CourierServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('is_cod_available', models.BooleanField(default=True)),
                ('is_express_available', models.BooleanField(default=False)),
                ('standard_delivery_days', models.IntegerField(default=3)),
                ('express_delivery_days', models.IntegerField(default=1)),
                ('courier_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courier.courierpartner')),
            ],
            options={
                'unique_together': {('courier_partner', 'pincode')},
            },
        ),
    ]
