# Generated by Django 5.2.1 on 2025-09-19 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0001_initial'),
    ]

    operations = [
    ]
