# Generated by Django 5.2.1 on 2025-09-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courierpartner',
            name='courier_type',
        ),
        migrations.AlterField(
            model_name='courierpartner',
            name='name',
            field=models.CharField(default='TPC', max_length=100),
        ),
    ]
