# Generated by Django 4.2.13 on 2025-11-05 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courier', '0001_initial'),
        ('orders', '0001_initial'),
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpcrecipient',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tpc_recipients', to='usermanagement.address'),
        ),
        migrations.AddField(
            model_name='couriershipment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courier_shipment', to='orders.order'),
        ),
    ]
